# Project: WIFI-HIFI
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/lib32" -L"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc C:/HubiC/CPP/IDE/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32/libwinmm.a -m32
INCS     = -I"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/include" -I"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/include" -I"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/hubiC/CPP/IDE/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = WIFI-HIFI.exe
CXXFLAGS = $(CXXINCS) -ansi -march=pentiumpro -Ofast -m32 -Wfatal-errors
CFLAGS   = $(INCS) -ansi -march=pentiumpro -Ofast -m32 -Wfatal-errors
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
